import { useState, useEffect } from "react";

function useWindowSize() {
  const [size, setSize] = useState({
    w: typeof window !== "undefined" ? window.innerWidth : 1200,
    h: typeof window !== "undefined" ? window.innerHeight : 800,
  });
  useEffect(() => {
    const handler = () => setSize({ w: window.innerWidth, h: window.innerHeight });
    window.addEventListener("resize", handler);
    return () => window.removeEventListener("resize", handler);
  }, []);
  return size;
}

const C = { black: "#000000", navy: "#14213D", amber: "#FCA311", silver: "#E5E5E5", white: "#FFFFFF", navyLight: "#1B2D4F", amberSoft: "rgba(252,163,17,0.10)", amberMuted: "rgba(252,163,17,0.6)", silverDark: "#CCCCCC", bg: "#F7F7F7", text1: "#14213D", text2: "#6B7280", text3: "#9CA3AF", danger: "#DC2626", dangerBg: "#FEE2E2", success: "#059669", successBg: "#D1FAE5", whatsapp: "#25D366" };
const F = "Helvetica, 'Helvetica Neue', sans-serif";
const R = { sm: 8, md: 12, lg: 16, xl: 24, pill: 999 };

function Box({ children, style }) { return <div style={{ background: C.white, borderRadius: R.md, padding: "10px 14px", marginBottom: 8, border: `1px solid ${C.silver}`, ...style }}>{children}</div>; }
function Btn({ children, primary, green, style, small }) { return <div style={{ background: green ? C.whatsapp : primary ? C.amber : C.silver, color: green || primary ? C.navy : C.text1, borderRadius: R.md, padding: small ? "8px 16px" : "13px 0", textAlign: "center", fontWeight: 700, fontSize: small ? 12 : 13, fontFamily: F, marginBottom: 8, cursor: "pointer", letterSpacing: 0.2, ...style }}>{children}</div>; }
function Inp({ p, style }) { return <div style={{ background: C.white, border: `1.5px solid ${C.silver}`, borderRadius: R.md, padding: "11px 14px", marginBottom: 8, color: C.text3, fontSize: 11, fontFamily: F, ...style }}>{p}</div>; }
function Lbl({ children }) { return <div style={{ fontSize: 10, color: C.text2, marginBottom: 3, fontWeight: 700, letterSpacing: 0.8, textTransform: "uppercase", fontFamily: F }}>{children}</div>; }
function Hdr({ l, t, r }) { return <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingBottom: 12, borderBottom: `1px solid ${C.silver}`, marginBottom: 16 }}><span style={{ fontSize: 12, color: C.text2, minWidth: 40, fontFamily: F }}>{l}</span><span style={{ fontWeight: 800, fontSize: 15, color: C.navy, fontFamily: F }}>{t}</span><span style={{ fontSize: 12, color: C.text2, minWidth: 40, textAlign: "right", fontFamily: F }}>{r}</span></div>; }
function Tab({ a = 0 }) { const items = [{ i: "🏠", l: "Home" }, { i: "🧭", l: "Explore" }, { i: "💰", l: "Wallet" }, { i: "👤", l: "Profile" }]; return <div style={{ display: "flex", borderTop: `1px solid ${C.silver}`, padding: "8px 0 6px", background: C.white }}>{items.map((t, i) => <div key={i} style={{ flex: 1, textAlign: "center", fontSize: 9, color: i === a ? C.navy : C.text3, fontWeight: i === a ? 800 : 500, fontFamily: F }}><div style={{ fontSize: 17, marginBottom: 1 }}>{t.i}</div>{t.l}{i === a && <div style={{ width: 4, height: 4, borderRadius: 4, background: C.amber, margin: "2px auto 0" }} />}</div>)}</div>; }
function Av({ s = 32, c = C.silver, style }) { return <div style={{ width: s, height: s, borderRadius: s, background: c, flexShrink: 0, ...style }} />; }
function Ch({ children, active }) { return <div style={{ display: "inline-block", padding: "6px 12px", borderRadius: R.pill, fontSize: 11, fontWeight: 600, background: active ? C.navy : C.bg, color: active ? C.amber : C.text1, fontFamily: F }}>{children}</div>; }
function Wrap({ children, style }) { return <div style={{ padding: 20, fontFamily: F, ...style }}>{children}</div>; }
function Shell({ children, tab = 0, noPad }) { return <div style={{ display: "flex", flexDirection: "column", height: "100%", fontFamily: F }}><div style={{ flex: 1, overflowY: "auto", padding: noPad ? 0 : 16 }}>{children}</div><Tab a={tab} /></div>; }
function Row2({ l, r }) { return <div style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: `1px solid ${C.silver}` }}><span style={{ fontSize: 12, color: C.text2, fontFamily: F }}>{l}</span><span style={{ fontSize: 12, fontWeight: 700, color: C.navy, fontFamily: F }}>{r}</span></div>; }

// ─── SCREENS ───
function SplashScreen() { return <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", background: `linear-gradient(170deg,${C.navy},${C.black})`, padding: 20 }}><div style={{ fontSize: 48, fontWeight: 900, color: C.white, fontFamily: F, letterSpacing: -2 }}>PoolUp</div><div style={{ fontSize: 11, color: C.amber, fontWeight: 700, marginTop: 8, letterSpacing: 2.5, textTransform: "uppercase" }}>Accountability Through Consequence</div><div style={{ fontSize: 11, color: C.amberMuted, marginTop: 4, fontStyle: "italic" }}>Paisa Lagao, Discipline Dikhao.</div></div>; }

function LoginScreen() { return <Wrap><div style={{ fontSize: 24, fontWeight: 900, color: C.navy, marginBottom: 2 }}>Welcome</div><div style={{ fontSize: 12, color: C.text2, marginBottom: 32 }}>Enter your phone number to get started</div><Lbl>MOBILE NUMBER</Lbl><div style={{ display: "flex", gap: 8 }}><div style={{ background: C.bg, borderRadius: R.md, padding: "11px 12px", fontSize: 13, fontWeight: 800, color: C.navy, fontFamily: F, border: `1.5px solid ${C.silver}` }}>+91</div><Inp p="98765 43210" style={{ flex: 1, marginBottom: 0 }} /></div><div style={{ height: 16 }} /><Btn primary>Send OTP →</Btn><div style={{ textAlign: "center", margin: "20px 0 12px", fontSize: 11, color: C.text3 }}>or continue with</div><div style={{ display: "flex", gap: 8 }}><Btn style={{ flex: 1 }}>Google</Btn><Btn style={{ flex: 1 }}> Apple</Btn></div></Wrap>; }

function OTPScreen() { return <Wrap><div style={{ fontSize: 10, color: C.text2, marginBottom: 16 }}>← Back</div><div style={{ fontSize: 24, fontWeight: 900, color: C.navy, marginBottom: 2 }}>Verify OTP</div><div style={{ fontSize: 12, color: C.text2, marginBottom: 24 }}>Sent to +91 98765 43210</div><div style={{ display: "flex", gap: 8, justifyContent: "center", marginBottom: 24 }}>{[4,2,8,6,1,""].map((d,i) => <div key={i} style={{ width: 38, height: 46, border: `2px solid ${d!==""?C.navy:C.silver}`, borderRadius: R.md, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800, color: C.navy, fontFamily: F, background: d!==""?C.amberSoft:C.white }}>{d}</div>)}</div><Btn primary>Verify & Continue</Btn><div style={{ textAlign: "center", marginTop: 16, fontSize: 12, color: C.text3 }}>Resend in <span style={{ color: C.amber, fontWeight: 700 }}>0:28</span></div></Wrap>; }

function ProfileSetupScreen() { return <Wrap><div style={{ fontSize: 18, fontWeight: 900, color: C.navy, marginBottom: 2 }}>Set Up Profile</div><div style={{ fontSize: 12, color: C.text2, marginBottom: 20 }}>Let your friends know who you are</div><div style={{ display: "flex", justifyContent: "center", marginBottom: 20 }}><div style={{ width: 68, height: 68, borderRadius: 68, background: C.bg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, color: C.text3, border: `2px dashed ${C.silverDark}` }}>📷</div></div><Lbl>FIRST NAME</Lbl><Inp p="Avanish" /><Lbl>LAST NAME</Lbl><Inp p="Sharma" /><Lbl>USERNAME</Lbl><Inp p="@avanish_fit" /><div style={{ fontSize: 10, color: C.success, marginTop: -4, marginBottom: 12 }}>✓ Available</div><Lbl>REFERRAL CODE (OPTIONAL)</Lbl><Inp p="e.g. POOL3A7K" /><Btn primary style={{ marginTop: 8 }}>Continue →</Btn></Wrap>; }

function GatewayScreen() { return <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", padding: 20 }}><div style={{ fontSize: 18, fontWeight: 900, color: C.navy, marginBottom: 2 }}>Ready to start? 🔥</div><div style={{ fontSize: 12, color: C.text2, marginBottom: 32, textAlign: "center" }}>Create a challenge or join one</div><div style={{ width: "100%" }}><div style={{ background: C.navy, borderRadius: R.lg, padding: 20, marginBottom: 12 }}><div style={{ fontSize: 15, fontWeight: 800, color: C.amber, fontFamily: F }}>Create a Pool</div><div style={{ fontSize: 11, color: "rgba(255,255,255,0.5)", marginTop: 4, fontFamily: F }}>Set the rules. Invite your squad.</div><div style={{ fontSize: 18, marginTop: 12, color: C.amber }}>→</div></div><div style={{ background: C.amber, borderRadius: R.lg, padding: 20 }}><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, fontFamily: F }}>Join via Code</div><div style={{ fontSize: 11, color: "rgba(20,33,61,0.6)", marginTop: 4, fontFamily: F }}>Got an invite? Enter the code.</div><div style={{ fontSize: 18, marginTop: 12, color: C.navy }}>→</div></div></div></div>; }

function CreateStep1() { return <Wrap><Hdr l="←" t="Create Pool" r="1/4" /><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, marginBottom: 16 }}>Name & Challenge</div><Lbl>POOL NAME</Lbl><Inp p="75 Hard Boyz 💪" /><Lbl>CHALLENGE TYPE</Lbl><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>{["75 Hard","Gym Streak","5K Run","Surya Namaskar","No Sugar","Custom"].map((t,i) => <Ch key={i} active={i===0}>{t}</Ch>)}</div><Lbl>DESCRIPTION</Lbl><Inp p="No excuses. 75 days of discipline." /><Lbl>POOL EMOJI</Lbl><div style={{ display: "flex", gap: 8, marginBottom: 16 }}>{["🔥","💪","🏃","🧘","🥗"].map((e,i) => <div key={i} style={{ width: 36, height: 36, borderRadius: R.sm, background: i===0?C.amberSoft:C.bg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 17, border: i===0?`2px solid ${C.amber}`:`1px solid ${C.silver}` }}>{e}</div>)}</div><Btn primary>Next →</Btn></Wrap>; }

function CreateStep2() { return <Wrap><Hdr l="←" t="Create Pool" r="2/4" /><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, marginBottom: 16 }}>Duration & Schedule</div><Lbl>DURATION</Lbl><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>{["21 days","30 days","60 days","75 days","Custom"].map((d,i) => <Ch key={i} active={i===1}>{d}</Ch>)}</div><Lbl>START DATE</Lbl><Inp p="Tomorrow, 5 Apr 2026" /><Lbl>DEADLINE</Lbl><Inp p="11:30 PM IST" /><Lbl>CHECK-IN WINDOW</Lbl><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}><Ch active>Full Day</Ch><Ch>Morning Only</Ch><Ch>Custom</Ch></div><Lbl>CHECK-IN TYPE</Lbl><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>{["📸 Photo","🎥 Video","👟 Steps","🏃 Strava"].map((t,i) => <Ch key={i} active={i===0}>{t}</Ch>)}</div><Btn primary>Next →</Btn></Wrap>; }

function CreateStep3() { return <Wrap><Hdr l="←" t="Create Pool" r="3/4" /><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, marginBottom: 16 }}>Stakes 💰</div><Lbl>BUY-IN</Lbl><div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}><div style={{ background: C.navy, color: C.amber, borderRadius: R.md, padding: "8px 14px", fontWeight: 900, fontSize: 18, fontFamily: F }}>₹499</div><div style={{ flex: 1 }}><div style={{ height: 6, background: C.silver, borderRadius: 3, position: "relative" }}><div style={{ position: "absolute", left: 0, top: 0, height: 6, width: "30%", background: C.amber, borderRadius: 3 }} /></div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 3 }}><span style={{ fontSize: 9, color: C.text3 }}>₹99</span><span style={{ fontSize: 9, color: C.text3 }}>₹5,000</span></div></div></div><Lbl>FINE PER MISS</Lbl><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>{["₹25","₹49","₹99","₹199","₹499"].map((f,i) => <Ch key={i} active={i===2}>{f}</Ch>)}</div><Lbl>ELIMINATION</Lbl><div style={{ display: "flex", gap: 6, marginBottom: 16 }}><Ch active>Off</Ch><Ch>3 misses</Ch><Ch>1 miss</Ch></div><Lbl>PAYOUT RULE</Lbl><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}><Ch active>Winner Takes All</Ch><Ch>Top 3</Ch><Ch>Proportional</Ch></div><Lbl>GRACE TOKENS</Lbl><div style={{ display: "flex", gap: 6, marginBottom: 16 }}>{["0","1","2","3"].map((g,i) => <Ch key={i} active={i===1}>{g}</Ch>)}</div><Btn primary>Review →</Btn></Wrap>; }

function CreateStep4() { return <Wrap><Hdr l="←" t="Create Pool" r="4/4" /><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, marginBottom: 12 }}>Review & Create</div><Box style={{ background: C.amberSoft, borderColor: C.amber }}><div style={{ fontSize: 13, fontWeight: 800, color: C.navy }}>🔥 75 Hard Boyz</div><div style={{ fontSize: 11, color: C.text2, marginTop: 2 }}>75 Hard · 30 days · Photo</div></Box>{[["Buy-in","₹499"],["Fine/miss","₹99"],["Elimination","Off"],["Payout","Winner Takes All"],["Grace Tokens","1"],["Start","5 Apr 2026"],["Deadline","11:30 PM IST"],["Platform Fee","5%"]].map(([k,v],i) => <Row2 key={i} l={k} r={v} />)}<div style={{ height: 12 }} /><Btn primary>Create Pool 🚀</Btn></Wrap>; }

function ShareInviteScreen() { return <Wrap style={{ textAlign: "center", paddingTop: 40 }}><div style={{ fontSize: 40 }}>🎉</div><div style={{ fontSize: 18, fontWeight: 900, color: C.navy, marginTop: 8 }}>Pool Created!</div><div style={{ fontSize: 12, color: C.text2, marginTop: 4, marginBottom: 24 }}>Share this code with your squad</div><div style={{ background: C.bg, borderRadius: R.lg, padding: 20, marginBottom: 20, border: `2px dashed ${C.silverDark}` }}><div style={{ fontSize: 30, fontWeight: 900, letterSpacing: 8, color: C.navy, fontFamily: F }}>X7K9P2</div><div style={{ fontSize: 10, color: C.text3, marginTop: 4 }}>Tap to copy</div></div><Btn green>📱 Share on WhatsApp</Btn><Btn>🔗 Copy Invite Link</Btn><Btn>📷 Show QR Code</Btn></Wrap>; }

function JoinCodeScreen() { return <Wrap><Hdr l="←" t="Join Pool" r="" /><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, marginBottom: 2 }}>Enter Invite Code</div><div style={{ fontSize: 12, color: C.text2, marginBottom: 24 }}>Got a code from your friend?</div><div style={{ display: "flex", gap: 8, justifyContent: "center", marginBottom: 24 }}>{["X","7","K","9","P",""].map((d,i) => <div key={i} style={{ width: 38, height: 46, border: `2px solid ${d?C.navy:C.silver}`, borderRadius: R.md, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 800, color: C.navy, fontFamily: F, background: d?C.amberSoft:C.white }}>{d}</div>)}</div><Btn primary>Find Pool →</Btn><div style={{ textAlign: "center", margin: "20px 0 12px", fontSize: 11, color: C.text3 }}>or</div><Btn>📷 Scan QR Code</Btn></Wrap>; }

function JoinConsentScreen() { return <Wrap><Hdr l="←" t="Join Pool" r="" /><Box style={{ background: C.amberSoft, borderColor: C.amber }}><div style={{ fontSize: 13, fontWeight: 800, color: C.navy }}>🔥 75 Hard Boyz</div><div style={{ fontSize: 11, color: C.text2 }}>30 days · ₹499 buy-in · ₹99/miss · 6/20</div></Box><div style={{ fontSize: 13, fontWeight: 700, color: C.navy, marginTop: 12, marginBottom: 8 }}>Pool Rules</div>{["Daily photo check-in before 11:30 PM IST","Miss = ₹99 auto-debit from UPI","1 grace token (one free skip)","Winner takes all after 30 days"].map((r,i) => <div key={i} style={{ fontSize: 11, color: C.text1, padding: "3px 0 3px 14px", position: "relative", fontFamily: F }}><span style={{ position: "absolute", left: 0, color: C.amber }}>•</span>{r}</div>)}<div style={{ background: "#FEF9E7", borderRadius: R.md, padding: 12, marginTop: 12, fontSize: 10, color: "#78350F", lineHeight: 1.6, border: "1px solid #FDE68A", fontFamily: F }}>⚠️ I authorise PoolUp to debit up to <b>₹99</b> per missed day for 30 days.</div><div style={{ display: "flex", alignItems: "center", gap: 8, margin: "12px 0" }}><div style={{ width: 20, height: 20, borderRadius: 4, background: C.navy, display: "flex", alignItems: "center", justifyContent: "center", color: C.amber, fontSize: 12, flexShrink: 0 }}>✓</div><div style={{ fontSize: 11, color: C.text1, fontFamily: F }}>I agree to the rules and auto-debit</div></div><Btn primary>Set Up UPI Autopay →</Btn></Wrap>; }

function JoinPayScreen() { return <Wrap style={{ textAlign: "center", paddingTop: 36 }}><div style={{ fontSize: 15, fontWeight: 800, color: C.navy, marginBottom: 16 }}>Pay Buy-in</div><div style={{ fontSize: 36, fontWeight: 900, color: C.navy, fontFamily: F }}>₹499</div><div style={{ fontSize: 11, color: C.text2, marginTop: 2, marginBottom: 24 }}>75 Hard Boyz · 30 days</div><Box style={{ textAlign: "left", display: "flex", alignItems: "center", gap: 12, borderColor: C.navy }}><div style={{ width: 32, height: 32, borderRadius: R.sm, background: C.navy, color: C.amber, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, flexShrink: 0 }}>UPI</div><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>UPI</div><div style={{ fontSize: 10, color: C.text3 }}>GPay, PhonePe, Paytm</div></div><div style={{ width: 16, height: 16, borderRadius: 16, border: `2px solid ${C.navy}`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><div style={{ width: 8, height: 8, borderRadius: 8, background: C.navy }} /></div></Box><Box style={{ textAlign: "left", display: "flex", alignItems: "center", gap: 12 }}><div style={{ width: 32, height: 32, borderRadius: R.sm, background: C.bg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, flexShrink: 0 }}>💳</div><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>Card</div><div style={{ fontSize: 10, color: C.text3 }}>Visa, Mastercard, RuPay</div></div><div style={{ width: 16, height: 16, borderRadius: 16, border: `2px solid ${C.silver}`, flexShrink: 0 }} /></Box><Btn primary style={{ marginTop: 8 }}>Pay ₹499 →</Btn><div style={{ fontSize: 9, color: C.text3, marginTop: 8 }}>Secured by Razorpay 🔒</div></Wrap>; }

function HomeScreen() { return <Shell tab={0}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}><div><div style={{ fontSize: 12, color: C.text2, fontFamily: F }}>Good morning</div><div style={{ fontSize: 18, fontWeight: 900, color: C.navy, fontFamily: F }}>Avanish 👋</div></div><div style={{ display: "flex", gap: 8, alignItems: "center" }}><div style={{ width: 32, height: 32, borderRadius: 32, background: C.amberSoft, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14 }}>🔔</div><Av s={32} c="#C7D2FE" /></div></div><Box style={{ background: C.amberSoft, borderColor: C.amber }}><div style={{ fontSize: 11, color: C.amber, fontWeight: 700 }}>⚡ 1 PENDING CHECK-IN</div><div style={{ fontSize: 12, color: C.text1, marginTop: 2, fontFamily: F }}>75 Hard Boyz · Deadline 11:30 PM</div></Box><Btn primary style={{ fontSize: 15, padding: "14px 0" }}>📸 Check In</Btn><div style={{ fontSize: 13, fontWeight: 800, color: C.navy, marginTop: 16, marginBottom: 8 }}>Active Pools</div>{[{n:"75 Hard Boyz",e:"🔥",p:"₹5,192",s:14,d:16},{n:"Morning 5K Club",e:"🏃",p:"₹2,400",s:7,d:23},{n:"No Maida January",e:"🥗",p:"₹1,800",s:21,d:9}].map((pool,i) => <Box key={i}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 800, color: C.navy, fontFamily: F }}>{pool.e} {pool.n}</div><div style={{ fontSize: 10, color: C.text2, marginTop: 2 }}>Pot: {pool.p} · {pool.d} days left</div></div><div style={{ textAlign: "right", flexShrink: 0, marginLeft: 12 }}><div style={{ fontSize: 15, fontWeight: 900, color: C.amber }}>🔥{pool.s}</div><div style={{ fontSize: 9, color: C.text3 }}>streak</div></div></div></Box>)}</Shell>; }

function PoolDetailScreen() { return <Shell tab={0} noPad><div style={{ background: C.navy, padding: 16 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 }}><span style={{ fontSize: 12, color: "rgba(255,255,255,0.5)" }}>← Back</span><span style={{ fontSize: 12, color: "rgba(255,255,255,0.5)" }}>⚙️</span></div><div style={{ fontSize: 18, fontWeight: 900, color: C.white, fontFamily: F }}>🔥 75 Hard Boyz</div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 16 }}>{[["Pot","₹5,192"],["Days","16"],["Members","8/20"],["Streak","🔥14"]].map(([k,v],i) => <div key={i} style={{ textAlign: "center" }}><div style={{ fontSize: 14, fontWeight: 900, color: C.white, fontFamily: F }}>{v}</div><div style={{ fontSize: 9, color: "rgba(255,255,255,0.5)" }}>{k}</div></div>)}</div></div><div style={{ display: "flex" }}>{["Feed","Leaderboard","Stats"].map((t,i) => <div key={i} style={{ flex: 1, textAlign: "center", padding: "10px 0", fontSize: 12, fontWeight: i===0?800:500, color: i===0?C.navy:C.text3, borderBottom: i===0?`2px solid ${C.amber}`:`1px solid ${C.silver}`, fontFamily: F }}>{t}</div>)}</div><div style={{ padding: 16 }}><div style={{ fontSize: 11, color: C.text2, marginBottom: 8 }}>Today · 6/8 checked in</div>{[{n:"Priya",t:"7:02 AM",c:"Morning run! 🏃‍♀️",s:14},{n:"Rahul",t:"8:15 AM",c:"Gym session 💪",s:12}].map((ck,i) => <Box key={i}><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}><Av s={26} c={["#C7D2FE","#FED7AA"][i]} /><div style={{ flex: 1 }}><span style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>{ck.n}</span> <span style={{ fontSize: 10, color: C.amber }}>🔥{ck.s}</span><div style={{ fontSize: 9, color: C.text3 }}>{ck.t}</div></div></div><div style={{ background: C.bg, borderRadius: R.sm, height: 72, marginBottom: 6, display: "flex", alignItems: "center", justifyContent: "center", color: C.text3, fontSize: 11 }}>[Check-in Photo]</div><div style={{ fontSize: 11, color: C.text1, fontFamily: F }}>{ck.c}</div><div style={{ fontSize: 12, marginTop: 6 }}>🔥12 💪5 👑3</div></Box>)}</div></Shell>; }

function LeaderboardScreen() { return <Shell tab={0}><Hdr l="←" t="Leaderboard" r="" /><div style={{ display: "flex", justifyContent: "center", alignItems: "flex-end", gap: 16, marginBottom: 20 }}>{[{n:"Rahul",s:12,m:"🥈"},{n:"Priya",s:14,m:"🥇"},{n:"You",s:10,m:"🥉"}].map((u,i) => <div key={i} style={{ textAlign: "center", marginTop: i===1?0:16 }}><Av s={i===1?44:36} c={["#FED7AA",C.amber,"#C7D2FE"][i]} style={{ margin: "0 auto 4px", border: i===1?`3px solid ${C.navy}`:"none" }} /><div style={{ fontSize: 18 }}>{u.m}</div><div style={{ fontSize: 11, fontWeight: 700, fontFamily: F }}>{u.n}</div><div style={{ fontSize: 10, color: C.amber, fontWeight: 700 }}>🔥{u.s}</div></div>)}</div>{[{r:4,n:"Amit",s:9,f:"₹198",p:"87%"},{r:5,n:"Sneha",s:8,f:"₹297",p:"80%"},{r:6,n:"Dev",s:6,f:"₹396",p:"73%"},{r:7,n:"Meera",s:4,f:"₹495",p:"67%"},{r:8,n:"Vikram",s:0,f:"₹594",p:"53%",out:true}].map((u,i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 0", borderBottom: `1px solid ${C.silver}`, opacity: u.out?0.4:1 }}><div style={{ width: 20, fontSize: 12, fontWeight: 700, color: C.text3, textAlign: "center", flexShrink: 0 }}>{u.r}</div><Av s={28} /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>{u.n}{u.out?" 💀":""}</div><div style={{ fontSize: 10, color: C.text2 }}>Fines: {u.f}</div></div><div style={{ textAlign: "right", flexShrink: 0 }}><div style={{ fontSize: 12, fontWeight: 800, color: C.amber }}>🔥{u.s}</div><div style={{ fontSize: 9, color: C.text3 }}>{u.p}</div></div></div>)}</Shell>; }

function CameraScreen() { return <div style={{ background: C.black, height: "100%", display: "flex", flexDirection: "column" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: 16 }}><div style={{ color: C.white, fontSize: 13, fontFamily: F }}>✕</div><div style={{ background: "rgba(255,255,255,0.12)", borderRadius: R.pill, padding: "4px 14px", fontSize: 11, color: C.white, fontFamily: F }}>🔥 75 Hard Boyz</div><div style={{ color: C.white, fontSize: 13 }}>🔄</div></div><div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ width: 150, height: 150, borderRadius: 150, border: `2px solid rgba(255,255,255,0.15)`, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ color: "rgba(255,255,255,0.25)", fontSize: 11, fontFamily: F }}>[Camera]</div></div></div><div style={{ display: "flex", justifyContent: "center", alignItems: "center", paddingBottom: 32, gap: 32 }}><div style={{ color: C.white, fontSize: 11, fontFamily: F }}>Front</div><div style={{ width: 58, height: 58, borderRadius: 58, background: C.white, border: `4px solid ${C.amber}` }} /><div style={{ width: 36 }} /></div></div>; }

function LivenessScreen() { return <div style={{ background: C.black, height: "100%", display: "flex", flexDirection: "column" }}><div style={{ display: "flex", justifyContent: "space-between", padding: 16 }}><div style={{ color: C.white, fontSize: 13 }}>✕</div><div style={{ color: C.white, fontSize: 13 }}>🔄</div></div><div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 20 }}><div style={{ background: C.amber, borderRadius: R.lg, padding: "16px 24px", textAlign: "center" }}><div style={{ fontSize: 9, color: C.navy, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase" }}>LIVENESS CHECK</div><div style={{ fontSize: 22, fontWeight: 900, color: C.navy, marginTop: 8, fontFamily: F }}>✌️ Show 2 Fingers</div><div style={{ fontSize: 10, color: "rgba(20,33,61,0.6)", marginTop: 4 }}>Hold steady</div></div><div style={{ width: 130, height: 130, borderRadius: 130, border: "2px solid rgba(255,255,255,0.15)" }} /></div><div style={{ display: "flex", justifyContent: "center", paddingBottom: 32 }}><div style={{ width: 58, height: 58, borderRadius: 58, background: C.white, border: `4px solid ${C.amber}` }} /></div></div>; }

function PreviewScreen() { return <div style={{ background: C.black, height: "100%", display: "flex", flexDirection: "column" }}><div style={{ padding: 16 }}><div style={{ color: C.white, fontSize: 12, background: "rgba(255,255,255,0.12)", borderRadius: R.pill, padding: "4px 14px", display: "inline-block", fontFamily: F }}>↩ Retake</div></div><div style={{ flex: 1, margin: "0 16px", background: "#111", borderRadius: R.md, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ color: "#444", fontSize: 12, fontFamily: F }}>[Photo Preview]</div></div><div style={{ padding: 16 }}><Inp p="Add a caption... 'Morning run! 🏃'" style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.12)", color: "rgba(255,255,255,0.4)" }} /><Btn primary>Submit Check-in ✓</Btn></div></div>; }

function CheckinSuccessScreen() { return <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", padding: 20, background: `linear-gradient(170deg,${C.black},${C.navy})` }}><div style={{ fontSize: 56 }}>🔥</div><div style={{ fontSize: 28, fontWeight: 900, color: C.white, fontFamily: F, marginTop: 8 }}>Day 15!</div><div style={{ fontSize: 13, color: C.amber, fontWeight: 700, marginTop: 4 }}>Streak: 14 days 🔥🔥</div><div style={{ fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 8 }}>+10 XP · Level 7</div><div style={{ background: "rgba(255,255,255,0.07)", borderRadius: R.lg, padding: 16, marginTop: 24, width: "100%", textAlign: "center", border: "1px solid rgba(255,255,255,0.1)" }}><div style={{ fontSize: 10, color: "rgba(255,255,255,0.35)" }}>YOU'RE #2 IN THE POOL</div><div style={{ fontSize: 13, color: C.white, fontWeight: 700, marginTop: 4, fontFamily: F }}>Tied with Priya at 🔥14!</div></div><div style={{ width: "100%", marginTop: 20 }}><Btn green>📱 Share on WhatsApp</Btn><Btn style={{ background: "rgba(255,255,255,0.08)", color: C.white }}>View Pool Feed →</Btn></div></div>; }

function FeedScreen() { return <Shell tab={0} noPad><div style={{ background: C.navy, padding: "12px 16px", display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontSize: 13, fontWeight: 800, color: C.white, fontFamily: F }}>🔥 75 Hard Boyz</div><div style={{ fontSize: 10, color: "rgba(255,255,255,0.45)" }}>Day 15 · 8 members</div></div><div style={{ textAlign: "right" }}><div style={{ fontSize: 15, fontWeight: 900, color: C.amber }}>₹5,192</div><div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)" }}>Pot</div></div></div><div style={{ padding: 16 }}><div style={{ fontSize: 11, color: C.text2, marginBottom: 8 }}>Today · 6/8 checked in</div>{[{n:"Priya",t:"7:02 AM",c:"Early bird 🐦",s:14,rx:"🔥14 💪8"},{n:"Rahul",t:"8:15 AM",c:"Gym done 💪",s:12,rx:"🔥9 💪6"},{n:"You",t:"9:30 AM",c:"Morning run!",s:14,rx:"🔥11 👑3"}].map((ck,i) => <Box key={i}><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}><Av s={24} c={["#C7D2FE","#FED7AA","#BBF7D0"][i]} /><div style={{ flex: 1 }}><span style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>{ck.n}</span> <span style={{ fontSize: 10, color: C.amber }}>🔥{ck.s}</span><div style={{ fontSize: 9, color: C.text3 }}>{ck.t}</div></div></div><div style={{ background: C.bg, borderRadius: R.sm, height: 56, marginBottom: 4, display: "flex", alignItems: "center", justifyContent: "center", color: C.text3, fontSize: 10 }}>[Photo]</div><div style={{ fontSize: 11, color: C.text1, fontFamily: F }}>{ck.c}</div><div style={{ fontSize: 12, marginTop: 4 }}>{ck.rx}</div></Box>)}</div></Shell>; }

function WallOfShameScreen() { return <Wrap><Hdr l="←" t="Feed Events" r="" /><div style={{ background: C.dangerBg, border: `2px solid ${C.danger}`, borderRadius: R.lg, padding: 20, textAlign: "center", marginBottom: 12 }}><div style={{ fontSize: 28 }}>🚨</div><div style={{ fontSize: 15, fontWeight: 900, color: C.danger, marginTop: 8, fontFamily: F }}>Vikram Missed!</div><div style={{ fontSize: 12, color: C.danger, marginTop: 2 }}>₹99 added to the pot</div><div style={{ fontSize: 11, color: "#991B1B", marginTop: 8 }}>Streak: 0 · Fines: ₹594</div></div><div style={{ background: C.successBg, border: `2px solid ${C.success}`, borderRadius: R.lg, padding: 20, textAlign: "center" }}><div style={{ fontSize: 28 }}>🎉</div><div style={{ fontSize: 15, fontWeight: 900, color: "#065F46", marginTop: 8, fontFamily: F }}>Priya hit 14 days!</div><div style={{ fontSize: 11, color: C.success, marginTop: 2 }}>Iron Will 🛡️ unlocked</div></div></Wrap>; }

function ReactionsScreen() { return <Wrap><Hdr l="←" t="React" r="" /><Box><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}><Av s={26} c="#C7D2FE" /><div><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>Priya</div><div style={{ fontSize: 9, color: C.text3 }}>7:02 AM</div></div></div><div style={{ background: C.bg, borderRadius: R.sm, height: 64, display: "flex", alignItems: "center", justifyContent: "center", color: C.text3, fontSize: 10 }}>[Photo]</div></Box><div style={{ display: "flex", justifyContent: "space-between", padding: "16px 8px" }}>{[{e:"🔥",l:"Fire",n:14,a:true},{e:"💪",l:"Flex",n:8},{e:"👑",l:"Crown",n:5},{e:"💀",l:"Skull",n:0},{e:"🙏",l:"Respect",n:2}].map((r,i) => <div key={i} style={{ textAlign: "center" }}><div style={{ fontSize: 24, width: 42, height: 42, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: R.md, background: r.a?C.amberSoft:"transparent", border: r.a?`2px solid ${C.amber}`:"2px solid transparent" }}>{r.e}</div><div style={{ fontSize: 9, color: C.text3, marginTop: 2 }}>{r.l}</div><div style={{ fontSize: 10, fontWeight: 700, color: C.navy }}>{r.n}</div></div>)}</div><div style={{ fontSize: 11, color: C.text3, textAlign: "center" }}>Double-tap for quick 🔥</div></Wrap>; }

function WalletScreen() { return <Shell tab={2}><div style={{ fontSize: 18, fontWeight: 900, color: C.navy, marginBottom: 12, fontFamily: F }}>Wallet 💰</div><div style={{ background: C.navy, borderRadius: R.lg, padding: 20, color: C.white, marginBottom: 12 }}><div style={{ fontSize: 10, color: "rgba(255,255,255,0.45)" }}>LOCKED IN POOLS</div><div style={{ fontSize: 28, fontWeight: 900, color: C.amber, marginTop: 4, fontFamily: F }}>₹1,497</div><div style={{ display: "flex", gap: 20, marginTop: 16 }}>{[["Won","₹3,500",C.success],["Fined","₹594",C.danger],["Net","+₹2,906",C.success]].map(([k,v,cl],i) => <div key={i}><div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)" }}>{k}</div><div style={{ fontSize: 13, fontWeight: 800, color: cl, fontFamily: F }}>{v}</div></div>)}</div></div><div style={{ fontSize: 13, fontWeight: 700, color: C.navy, marginBottom: 8 }}>Active Pools</div>{[["75 Hard Boyz","₹499 · ₹198 fined","₹5,192"],["Morning 5K","₹499 · ₹0 fined","₹2,400"],["No Maida","₹499 · ₹0 fined","₹1,800"]].map(([n,d,p],i) => <Box key={i}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>{n}</div><div style={{ fontSize: 10, color: C.text2 }}>{d}</div></div><div style={{ fontSize: 12, fontWeight: 800, color: C.amber, flexShrink: 0, marginLeft: 8 }}>{p}</div></div></Box>)}<div style={{ display: "flex", gap: 8, marginTop: 8 }}><Btn small style={{ flex: 1 }}>📋 Ledger</Btn><Btn small style={{ flex: 1 }}>💳 Methods</Btn></div></Shell>; }

function LedgerScreen() { return <Wrap><Hdr l="←" t="Transactions" r="" />{[{t:"deposit",d:"Buy-in: 75 Hard",a:"-₹499",c:C.danger,dt:"5 Apr",i:"🏦"},{t:"fine",d:"Missed Day 8",a:"-₹99",c:C.danger,dt:"12 Apr",i:"💸"},{t:"payout",d:"Won: Morning 5K",a:"+₹3,500",c:C.success,dt:"1 Apr",i:"💰"},{t:"powerup",d:"Shield bought",a:"-₹49",c:C.text2,dt:"28 Mar",i:"🛡️"}].map((tx,i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, padding: "8px 0", borderBottom: `1px solid ${C.silver}` }}><div style={{ width: 28, height: 28, borderRadius: R.sm, background: tx.t==="payout"?C.successBg:tx.t==="fine"?C.dangerBg:C.bg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, flexShrink: 0 }}>{tx.i}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: 600, fontFamily: F }}>{tx.d}</div><div style={{ fontSize: 10, color: C.text3 }}>{tx.dt}</div></div><div style={{ fontSize: 13, fontWeight: 800, color: tx.c, fontFamily: F, flexShrink: 0 }}>{tx.a}</div></div>)}</Wrap>; }

function PaymentMethodsScreen() { return <Wrap><Hdr l="←" t="Payment Methods" r="" /><Lbl>DEFAULT UPI</Lbl><Box style={{ display: "flex", alignItems: "center", gap: 12 }}><div style={{ fontSize: 18, flexShrink: 0 }}>📱</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 700, fontFamily: F }}>avanish@okaxis</div><div style={{ fontSize: 10, color: C.success }}>✓ Verified</div></div><div style={{ fontSize: 11, color: C.amber, fontWeight: 700, flexShrink: 0 }}>Edit</div></Box><Lbl>SAVED CARDS</Lbl><Box style={{ display: "flex", alignItems: "center", gap: 12 }}><div style={{ fontSize: 16, flexShrink: 0 }}>💳</div><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 600, fontFamily: F }}>HDFC •••• 4521</div><div style={{ fontSize: 10, color: C.text3 }}>Visa · 08/27</div></div></Box><Btn style={{ marginTop: 8 }}>+ Add Method</Btn><Lbl>PAYOUT ACCOUNT</Lbl><Box style={{ display: "flex", alignItems: "center", gap: 12 }}><div style={{ fontSize: 16, flexShrink: 0 }}>🏦</div><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 600, fontFamily: F }}>avanish@okaxis</div><div style={{ fontSize: 10, color: C.text3 }}>Instant UPI payout</div></div></Box></Wrap>; }

function ProfileScreen() { return <Shell tab={3} noPad><div style={{ background: C.navy, padding: 20, textAlign: "center" }}><Av s={56} c="#C7D2FE" style={{ margin: "0 auto", border: `3px solid ${C.amber}` }} /><div style={{ fontSize: 15, fontWeight: 900, color: C.white, marginTop: 8, fontFamily: F }}>Avanish Sharma</div><div style={{ fontSize: 11, color: "rgba(255,255,255,0.45)" }}>@avanish_fit · Level 7 · ⭐ Pro</div><div style={{ display: "flex", justifyContent: "center", gap: 20, marginTop: 16 }}>{[["XP","1,840"],["Pools","5"],["Wins","60%"],["Earned","₹3.5K"]].map(([k,v],i) => <div key={i} style={{ textAlign: "center" }}><div style={{ fontSize: 14, fontWeight: 900, color: C.white, fontFamily: F }}>{v}</div><div style={{ fontSize: 9, color: "rgba(255,255,255,0.4)" }}>{k}</div></div>)}</div></div><div style={{ padding: 16 }}><div style={{ fontSize: 13, fontWeight: 700, color: C.navy, marginBottom: 8 }}>Discipline Score</div><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 16 }}><div style={{ flex: 1, height: 8, background: C.silver, borderRadius: 4 }}><div style={{ height: 8, background: C.amber, borderRadius: 4, width: "87%" }} /></div><div style={{ fontSize: 13, fontWeight: 900, color: C.amber }}>87%</div></div><div style={{ fontSize: 13, fontWeight: 700, color: C.navy, marginBottom: 8 }}>Badges</div><div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 16 }}>{["👣 Pehla Kadam","🦾 Iron Will","💎 Diamond Hands","🤑 Pot Raja"].map((badge,i) => <div key={i} style={{ background: C.bg, borderRadius: R.pill, padding: "5px 10px", fontSize: 10, fontWeight: 600 }}>{badge}</div>)}</div><div style={{ fontSize: 13, fontWeight: 700, color: C.navy, marginBottom: 8 }}>Pool History</div>{[["75 Hard","🏆 Won · ₹3,500"],["Morning 5K","#3 · ₹0"]].map(([n,d],i) => <Box key={i}><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>{n}</div><div style={{ fontSize: 10, color: C.text2 }}>{d}</div></Box>)}</div></Shell>; }

function BadgesScreen() { return <Wrap><Hdr l="←" t="Badges" r="" /><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>{[{e:"👣",n:"Pehla Kadam",d:"First pool",r:"Common",ok:true},{e:"🦾",n:"Iron Will",d:"30-day streak",r:"Uncommon",ok:true},{e:"💎",n:"Diamond Hands",d:"100% in pool",r:"Rare",ok:true},{e:"🤑",n:"Pot Raja",d:"Win 3+",r:"Rare",ok:true},{e:"👑",n:"Untouchable",d:"5× 100%",r:"Epic"},{e:"🏆",n:"Centurion",d:"100-day streak",r:"Legendary"},{e:"💰",n:"Lakhpati",d:"₹1L+ earned",r:"Legendary"},{e:"🏏",n:"IPL Survivor",d:"Pool in IPL",r:"Seasonal"}].map((badge,i) => <div key={i} style={{ background: badge.ok?C.white:C.bg, border: badge.ok?`1px solid ${C.silver}`:`1px dashed ${C.silverDark}`, borderRadius: R.md, padding: 12, textAlign: "center", opacity: badge.ok?1:0.4 }}><div style={{ fontSize: 22 }}>{badge.e}</div><div style={{ fontSize: 11, fontWeight: 700, marginTop: 3, fontFamily: F }}>{badge.n}</div><div style={{ fontSize: 9, color: C.text3 }}>{badge.d}</div><div style={{ fontSize: 8, color: badge.r==="Legendary"?C.amber:badge.r==="Epic"?"#8B5CF6":C.text3, fontWeight: 700, marginTop: 3, textTransform: "uppercase" }}>{badge.r}{badge.ok?" ✓":""}</div></div>)}</div></Wrap>; }

function SettingsScreen() { return <Wrap><Hdr l="←" t="Settings" r="" />{["Profile","Notifications","Language","Payment Methods","PoolUp Pro","Privacy Policy","Terms of Service","Help & Support","Delete Account","Log Out"].map((item,i) => <div key={i} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 0", borderBottom: `1px solid ${C.silver}` }}><span style={{ fontSize: 13, color: i>=8?C.danger:C.text1, fontWeight: i>=8?600:400, fontFamily: F }}>{item}</span>{i<8 && <span style={{ fontSize: 12, color: C.text3 }}>→</span>}</div>)}</Wrap>; }

function ExploreScreen() { return <Shell tab={1}><div style={{ fontSize: 18, fontWeight: 900, color: C.navy, marginBottom: 12, fontFamily: F }}>Explore 🧭</div><Inp p="🔍 Search pools, creators..." /><div style={{ display: "flex", gap: 6, marginBottom: 12, flexWrap: "wrap" }}>{["🔥 Trending","💪 Fitness","🧘 Wellness","📚 Productivity"].map((cat,i) => <Ch key={i} active={i===0}>{cat}</Ch>)}</div><div style={{ fontSize: 12, fontWeight: 700, color: C.navy, marginBottom: 8 }}>Starting Soon</div>{[{n:"30-Day Gym Streak",c:"@fitcoach_raj ✓",m:"18/20",b:"₹499",d:"In 2 days"},{n:"IPL Fitness",c:"@muscleblaze ✓",m:"142/200",b:"FREE",d:"Tomorrow"},{n:"Surya Namaskar 21",c:"@yoga_priya ✓",m:"45/50",b:"₹99",d:"In 5 days"}].map((p,i) => <Box key={i}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: 700, fontFamily: F }}>{p.n}</div><div style={{ fontSize: 10, color: C.text2 }}>{p.c} · {p.m}</div><div style={{ fontSize: 10, color: C.amber, fontWeight: 600 }}>{p.d}</div></div><div style={{ textAlign: "right", flexShrink: 0, marginLeft: 8 }}><div style={{ fontSize: 12, fontWeight: 800, color: C.navy }}>{p.b}</div></div></div></Box>)}</Shell>; }

function PowerUpsScreen() { return <Wrap><Hdr l="←" t="Power-Ups ⚡" r="" />{[{e:"🛡️",n:"Shield",p:"₹49",d:"Block one fine"},{e:"🎲",n:"Double Down",p:"₹99",d:"2× fine for everyone"},{e:"💡",n:"Spotlight",p:"₹29",d:"Pin check-in to top"},{e:"⏰",n:"Alarm Bomb",p:"₹29",d:"Wake-up call via WhatsApp"},{e:"❄️",n:"Streak Freeze",p:"₹149",d:"Streak preserved, fine applies"},{e:"👻",n:"Ghost Mode",p:"₹49",d:"Hide status for 1 day"}].map((pw,i) => <div key={i} style={{ display: "flex", gap: 12, alignItems: "center", padding: "12px 0", borderBottom: `1px solid ${C.silver}` }}><div style={{ fontSize: 24, width: 32, textAlign: "center", flexShrink: 0 }}>{pw.e}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 700, fontFamily: F }}>{pw.n}</div><div style={{ fontSize: 10, color: C.text2 }}>{pw.d}</div></div><div style={{ background: C.amber, color: C.navy, borderRadius: R.sm, padding: "6px 12px", fontSize: 12, fontWeight: 800, fontFamily: F, flexShrink: 0 }}>{pw.p}</div></div>)}</Wrap>; }

function NotificationsScreen() { return <Wrap><Hdr l="←" t="Notifications" r="" />{[{i:"🚨",t:"3 hours left!",b:"75 Hard Boyz · Check in now",tm:"9:30 PM",u:true},{i:"💸",t:"Fine charged",b:"₹99 added to pot",tm:"12:01 AM",u:true},{i:"🔥",t:"14-day streak!",b:"You're in the top 3",tm:"Yesterday"},{i:"🚀",t:"Pool is LIVE!",b:"Morning 5K started",tm:"2d ago"},{i:"🎉",t:"You won ₹3,500!",b:"Payout processing",tm:"1w ago"}].map((n,i) => <div key={i} style={{ display: "flex", gap: 12, padding: 12, borderBottom: `1px solid ${C.silver}`, background: n.u?C.amberSoft:"transparent", margin: "0 -20px", paddingLeft: 20, paddingRight: 20 }}><div style={{ fontSize: 18, flexShrink: 0 }}>{n.i}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: n.u?800:500, fontFamily: F }}>{n.t}</div><div style={{ fontSize: 10, color: C.text2 }}>{n.b}</div></div><div style={{ fontSize: 9, color: C.text3, flexShrink: 0 }}>{n.tm}</div></div>)}</Wrap>; }

function FineAlertScreen() { return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%", padding: 20, background: "rgba(0,0,0,0.6)" }}><div style={{ background: C.white, borderRadius: R.xl, padding: 24, width: "100%", textAlign: "center" }}><div style={{ fontSize: 40 }}>💸</div><div style={{ fontSize: 18, fontWeight: 900, color: C.danger, marginTop: 8, fontFamily: F }}>You Missed Today</div><div style={{ fontSize: 13, color: C.text1, marginTop: 8, fontFamily: F }}>75 Hard Boyz</div><div style={{ fontSize: 28, fontWeight: 900, color: C.navy, marginTop: 8, fontFamily: F }}>-₹99</div><div style={{ fontSize: 11, color: C.text2, marginTop: 2 }}>Debited via UPI Autopay</div><div style={{ background: "#FEF9E7", borderRadius: R.md, padding: 12, marginTop: 16, fontSize: 11, color: "#78350F", border: "1px solid #FDE68A" }}>Streak: 0 · Fines: ₹297 · Pot: ₹5,291</div><div style={{ marginTop: 16 }}><Btn primary>OK, I'll do better tomorrow</Btn></div><div style={{ fontSize: 10, color: C.text3, marginTop: 4 }}>Grace tokens: 0</div></div></div>; }

function PayoutSuccessScreen() { return <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100%", padding: 20, background: `linear-gradient(170deg,${C.black},${C.navy})` }}><div style={{ fontSize: 52 }}>🎉</div><div style={{ fontSize: 11, color: "rgba(255,255,255,0.45)", marginTop: 8, letterSpacing: 2, textTransform: "uppercase" }}>CONGRATULATIONS</div><div style={{ fontSize: 13, color: C.white, fontWeight: 600, marginTop: 4, fontFamily: F }}>You won 75 Hard Boyz</div><div style={{ fontSize: 40, fontWeight: 900, color: C.amber, marginTop: 12, fontFamily: F }}>₹4,932</div><div style={{ fontSize: 11, color: "rgba(255,255,255,0.35)", marginTop: 2 }}>Pot: ₹5,192 · Fee: ₹260</div><div style={{ background: "rgba(255,255,255,0.06)", borderRadius: R.lg, padding: 16, marginTop: 20, width: "100%", border: "1px solid rgba(255,255,255,0.08)" }}>{[["Streak","30 days 🔥"],["Compliance","100% 💎"],["Fines","₹0"],["Badge","Diamond Hands"]].map(([k,v],i) => <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "5px 0", fontSize: 12 }}><span style={{ color: "rgba(255,255,255,0.45)" }}>{k}</span><span style={{ color: C.white, fontWeight: 700, fontFamily: F }}>{v}</span></div>)}</div><div style={{ width: "100%", marginTop: 20 }}><Btn green>📱 Share on WhatsApp</Btn><Btn style={{ background: "rgba(255,255,255,0.08)", color: C.white }}>View Wallet →</Btn></div><div style={{ fontSize: 9, color: "rgba(255,255,255,0.25)", marginTop: 12 }}>UTR: 402615XXXXXX</div></div>; }

// ─── SCREEN MAP ───
const SCREENS = {
  splash:{name:"Splash",group:"Auth",desc:"App launch"},login:{name:"Login",group:"Auth",desc:"Phone entry"},otp:{name:"OTP Verify",group:"Auth",desc:"6-digit code"},profileSetup:{name:"Profile Setup",group:"Auth",desc:"Name & username"},gateway:{name:"Gateway",group:"Auth",desc:"Create or Join"},
  createStep1:{name:"Create: Name",group:"Pool Create",desc:"Name & type"},createStep2:{name:"Create: Schedule",group:"Pool Create",desc:"Duration & time"},createStep3:{name:"Create: Stakes",group:"Pool Create",desc:"Buy-in & rules"},createStep4:{name:"Create: Review",group:"Pool Create",desc:"Confirm"},shareInvite:{name:"Share Invite",group:"Pool Create",desc:"WhatsApp & QR"},
  joinCode:{name:"Enter Code",group:"Pool Join",desc:"Invite code"},joinConsent:{name:"Consent",group:"Pool Join",desc:"Rules & mandate"},joinPay:{name:"Payment",group:"Pool Join",desc:"Razorpay"},
  home:{name:"Home",group:"Dashboard",desc:"Pool cards"},poolDetail:{name:"Pool Detail",group:"Dashboard",desc:"Feed & pot"},leaderboard:{name:"Leaderboard",group:"Dashboard",desc:"Rankings"},
  camera:{name:"Camera",group:"Check-in",desc:"Take photo"},liveness:{name:"Liveness",group:"Check-in",desc:"Verification"},preview:{name:"Preview",group:"Check-in",desc:"Review & caption"},checkinSuccess:{name:"Success",group:"Check-in",desc:"Streak confirmed"},
  feed:{name:"Pool Feed",group:"Social",desc:"Check-ins"},wallOfShame:{name:"Wall of Shame",group:"Social",desc:"Miss & milestone"},reactions:{name:"Reactions",group:"Social",desc:"React picker"},
  wallet:{name:"Wallet",group:"Wallet",desc:"Balances"},ledger:{name:"Ledger",group:"Wallet",desc:"Transactions"},paymentMethods:{name:"Methods",group:"Wallet",desc:"UPI & cards"},
  profile:{name:"Profile",group:"Profile",desc:"Stats & badges"},badges:{name:"Badges",group:"Profile",desc:"Achievements"},settings:{name:"Settings",group:"Profile",desc:"Preferences"},
  explore:{name:"Explore",group:"Discover",desc:"Public pools"},powerups:{name:"Power-Ups",group:"Discover",desc:"Shop"},notifications:{name:"Notifications",group:"Discover",desc:"Alerts"},
  fineAlert:{name:"Fine Alert",group:"Overlays",desc:"Miss modal"},payoutSuccess:{name:"Payout!",group:"Overlays",desc:"Win celebration"},
};
const GROUPS = [...new Set(Object.values(SCREENS).map(s => s.group))];
const RENDERERS = {splash:SplashScreen,login:LoginScreen,otp:OTPScreen,profileSetup:ProfileSetupScreen,gateway:GatewayScreen,createStep1:CreateStep1,createStep2:CreateStep2,createStep3:CreateStep3,createStep4:CreateStep4,shareInvite:ShareInviteScreen,joinCode:JoinCodeScreen,joinConsent:JoinConsentScreen,joinPay:JoinPayScreen,home:HomeScreen,poolDetail:PoolDetailScreen,leaderboard:LeaderboardScreen,camera:CameraScreen,liveness:LivenessScreen,preview:PreviewScreen,checkinSuccess:CheckinSuccessScreen,feed:FeedScreen,wallOfShame:WallOfShameScreen,reactions:ReactionsScreen,wallet:WalletScreen,ledger:LedgerScreen,paymentMethods:PaymentMethodsScreen,profile:ProfileScreen,badges:BadgesScreen,settings:SettingsScreen,explore:ExploreScreen,powerups:PowerUpsScreen,notifications:NotificationsScreen,fineAlert:FineAlertScreen,payoutSuccess:PayoutSuccessScreen};

export default function App() {
  const [screen, setScreen] = useState("splash");
  const [group, setGroup] = useState("Auth");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const { w: width, h: height } = useWindowSize();
  const isMobile = width < 640;

  const isDark = ["splash","camera","liveness","preview","checkinSuccess","payoutSuccess","fineAlert"].includes(screen);
  const Comp = RENDERERS[screen];

  const PHONE_W = 292;
  const PHONE_H = 600;

  // Space consumed by UI chrome (title/topbar + pills row + padding)
  // Desktop: 16pt + ~50title + 12gap + 28pills + 16pb = 122
  // Mobile: 64pt (topbar+gap) + 12gap + 28pills + 20pb = 124
  const vOverhead = isMobile ? 124 : 122;
  const hOverhead = isMobile ? 32 : 192 + 32; // sidebar + padding

  const scaleW = (width - hOverhead) / PHONE_W;
  const scaleH = (height - vOverhead) / PHONE_H;
  const scale = Math.min(1, scaleW, scaleH);
  const phoneW = Math.round(PHONE_W * scale);
  const phoneH = Math.round(PHONE_H * scale);

  const SidebarContent = () => (
    <>
      <div style={{ flex: 1, overflowY: "auto", padding: "0 6px" }}>
        {GROUPS.map(g => <div key={g} style={{ marginBottom: 2 }}>
          <div onClick={() => setGroup(g)} style={{ fontSize: 9, fontWeight: 700, color: group===g?C.amber:"rgba(255,255,255,0.3)", padding: "7px 6px 3px", cursor: "pointer", textTransform: "uppercase", letterSpacing: 1.2, fontFamily: F }}>{g}</div>
          {group===g && Object.entries(SCREENS).filter(([,v]) => v.group===g).map(([id,s]) => <div key={id} onClick={() => { setScreen(id); setDrawerOpen(false); }} style={{ padding: "5px 10px", borderRadius: 6, cursor: "pointer", fontSize: 11, fontWeight: screen===id?700:400, color: screen===id?C.amber:"rgba(255,255,255,0.5)", background: screen===id?C.amberSoft:"transparent", marginBottom: 1, fontFamily: F }}>{s.name}</div>)}
        </div>)}
      </div>
      <div style={{ padding: "6px 12px", borderTop: "1px solid rgba(255,255,255,0.06)", fontSize: 8, color: "rgba(255,255,255,0.18)", flexShrink: 0 }}>{Object.keys(SCREENS).length} screens · Helvetica</div>
    </>
  );

  return (
    <div style={{ display: "flex", height: "100vh", background: C.black, fontFamily: F, color: C.text1, overflow: "hidden" }}>

      {/* Desktop sidebar */}
      {!isMobile && (
        <div style={{ width: 192, background: C.navy, display: "flex", flexDirection: "column", flexShrink: 0, height: "100vh" }}>
          <div style={{ padding: "14px 12px 8px", flexShrink: 0 }}>
            <div style={{ fontSize: 20, fontWeight: 900, color: C.amber, fontFamily: F, letterSpacing: -1 }}>PoolUp</div>
            <div style={{ fontSize: 8, color: "rgba(255,255,255,0.3)", fontWeight: 600, letterSpacing: 1.5, marginTop: 2 }}>WIREFRAMES v2.0</div>
          </div>
          <SidebarContent />
        </div>
      )}

      {/* Mobile top bar */}
      {isMobile && (
        <div style={{ position: "fixed", top: 0, left: 0, right: 0, zIndex: 100, background: C.navy, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 16px", flexShrink: 0 }}>
          <div>
            <div style={{ fontSize: 18, fontWeight: 900, color: C.amber, fontFamily: F, letterSpacing: -0.5 }}>PoolUp</div>
            <div style={{ fontSize: 8, color: "rgba(255,255,255,0.3)", letterSpacing: 1.5 }}>WIREFRAMES v2.0</div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: C.white, fontFamily: F }}>{SCREENS[screen].name}</div>
            <div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)" }}>{SCREENS[screen].group}</div>
          </div>
          <div onClick={() => setDrawerOpen(true)} style={{ color: C.amber, fontSize: 22, cursor: "pointer", lineHeight: 1, marginLeft: 12 }}>☰</div>
        </div>
      )}

      {/* Mobile drawer overlay */}
      {isMobile && drawerOpen && (
        <div style={{ position: "fixed", inset: 0, zIndex: 200, background: "rgba(0,0,0,0.7)" }} onClick={() => setDrawerOpen(false)}>
          <div style={{ position: "absolute", left: 0, top: 0, bottom: 0, width: 240, background: C.navy, display: "flex", flexDirection: "column", overflow: "hidden" }} onClick={e => e.stopPropagation()}>
            <div style={{ padding: "14px 12px 8px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexShrink: 0 }}>
              <div>
                <div style={{ fontSize: 20, fontWeight: 900, color: C.amber, fontFamily: F, letterSpacing: -1 }}>PoolUp</div>
                <div style={{ fontSize: 8, color: "rgba(255,255,255,0.3)", fontWeight: 600, letterSpacing: 1.5, marginTop: 2 }}>WIREFRAMES v2.0</div>
              </div>
              <div onClick={() => setDrawerOpen(false)} style={{ color: "rgba(255,255,255,0.5)", fontSize: 20, cursor: "pointer", lineHeight: 1, marginTop: 2 }}>✕</div>
            </div>
            <SidebarContent />
          </div>
        </div>
      )}

      {/* Center content — no scroll, everything fits */}
      <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: isMobile ? `${52 + 12}px 16px 20px` : 16, minWidth: 0, overflow: "hidden" }}>

        {!isMobile && (
          <div style={{ textAlign: "center", marginBottom: 12, flexShrink: 0 }}>
            <div style={{ fontSize: 17, fontWeight: 800, color: C.white, fontFamily: F }}>{SCREENS[screen].name}</div>
            <div style={{ fontSize: 10, color: "rgba(255,255,255,0.35)", marginTop: 2, fontFamily: F }}>{SCREENS[screen].group} → {SCREENS[screen].desc}</div>
          </div>
        )}

        {/* Phone mockup — outer box is the scaled visual size, inner div is full 292×600 scaled via CSS transform */}
        <div style={{ width: phoneW, height: phoneH, borderRadius: Math.round(34 * scale), overflow: "hidden", boxShadow: "0 0 0 3px #222, 0 0 60px rgba(252,163,17,0.06)", flexShrink: 0, position: "relative" }}>
          <div style={{ width: PHONE_W, height: PHONE_H, transform: `scale(${scale})`, transformOrigin: "top left" }}>
            <div style={{ height: 32, background: isDark?C.black:C.white, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 18px", fontSize: 10, color: isDark?C.white:C.black, fontWeight: 600, fontFamily: F, position: "relative", zIndex: 2 }}>
              <span>9:41</span>
              <div style={{ width: 68, height: 18, background: C.black, borderRadius: 9, position: "absolute", left: "50%", transform: "translateX(-50%)", top: 5 }} />
              <span style={{ fontSize: 9 }}>📶 🔋</span>
            </div>
            <div style={{ height: PHONE_H - 32, background: isDark?C.black:C.white, overflowY: "auto", overflowX: "hidden" }}>{Comp && <Comp />}</div>
          </div>
        </div>

        {/* Screen quick-nav — single row, horizontally scrollable, fixed height */}
        <div style={{ display: "flex", gap: 4, marginTop: 12, flexShrink: 0, overflowX: "auto", width: "100%", justifyContent: "center", paddingBottom: 2 }}>
          {Object.entries(SCREENS).filter(([,v]) => v.group===group).map(([id,s]) => <div key={id} onClick={() => setScreen(id)} style={{ padding: "4px 10px", borderRadius: 6, fontSize: 10, cursor: "pointer", fontWeight: screen===id?700:400, background: screen===id?C.amber:"rgba(255,255,255,0.06)", color: screen===id?C.navy:"rgba(255,255,255,0.4)", fontFamily: F, whiteSpace: "nowrap", flexShrink: 0 }}>{s.name}</div>)}
        </div>
      </div>
    </div>
  );
}
